export const HOSPITAL = {
  "id": "바이오애드랩",
  "name": "바이오애드랩",
  "code": "바이",
  "color": "#f59e0b",
  "monthlyPublishGoal": 8,
  "seoTitle": "바이오애드랩 건강 정보",
  "description": "",
  "alternateNames": [],
  "knowsAbout": [],
  "telephone": "",
  "streetAddress": "",
  "addressLocality": "",
  "addressRegion": "",
  "postalCode": "",
  "doctorName": "",
  "doctorTitle": "",
  "logoUrl": "",
  "imageUrl": "",
  "sameAs": [],
  "founder": "",
  "areaServed": [],
  "about": [],
  "cmsUrl": "https://bioaddlabgeo.web.app",
  "siteUrl": "",
  "schemaProfile": "business",
  "firebaseApiKey": "AIzaSyBPa4_gNO-BCG5yGhl3atBBtKkMGroX6nc",
  "firebaseProjectId": "bioaddlabgeo"
} as const;
